version: "3.9"

x-logging:
  &loki-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

networks:
  apps:

services:
  pythonapp:
    build: ../app_python/
    restart: always
    ports:
      - "8000:8000"
    networks:
      - apps
    logging: *loki-logging

  kotlinapp:
    build: ../app_kotlin/
    restart: always
    ports:
      - "8080:8080"
    networks:
      - apps
    logging: *loki-logging

  prometheus:
    build: ./prometheus/
    restart: always
    ports:
      - "9090:9090"
    networks:
      - apps
    logging: *loki-logging

  loki:
    image: grafana/loki:2.6.1
    volumes:
      - ./config:/etc/loki/
    ports:
      - "3100"
    command: "-config.file=/etc/loki/loki.yaml -target=query-frontend -frontend.downstream-url=http://loki-read:3100"
    networks:
      - apps
    logging: *loki-logging

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./loki/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - apps
    logging: *loki-logging

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    networks:
      - apps
    logging: *loki-logging

